# Generated by Django 4.2.7 on 2023-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_user_user_type_user_is_admin_user_is_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False, verbose_name='Is administrator'),
        ),
    ]
