# Generated by Django 4.2.6 on 2023-11-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
